export const USER_LIST = 'USER_LIST';
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const EDIT_NOTIFICATION = 'EDIT_NOTIFICATION';
